version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile  # optional if named Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # map container port 80 (nginx) to localhost:3000
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
